### ISSUE TITLE
apt-local: command not found

### ISSUE THREAD

**Issue by quancs** [ashwinvis/apt-local#1]
* apt-local version: 0.0.2b1
* Python version: 3.8
* Operating System: Ubuntu 20

### Description

`quancs@DESKTOP-EBQH60O:~$ pip install apt-local --user`
Requirement already satisfied: apt-local in ./.local/lib/python3.8/site-packages (0.0.2b1)
`quancs@DESKTOP-EBQH60O:~$ apt-local set-path ~/.local/apt-cache`
apt-local: command not found

**Comment by quancs** [comment]
The same for Ubuntu 18

**Comment by ashwinvis** [comment]
@quancs Check

```sh
echo $PATH
```

and it should contain `$HOME/.local/bin`. If not you could append that path as follows by adding this to `~/,bashrc`

```sh
export PATH="$HOME/.local/bin:$PATH"
```
